// Import the configureStore and createSlice functions from Redux Toolkit
// import { configureStore } from "@reduxjs/toolkit"
import { createSlice } from "@reduxjs/toolkit";


//Define the initial state for the counter
const initialState = {
    value: 0,
}


// Create a slice for the counter with createSlice
// createSlice takes an object to function 
export const CounterSlice = createSlice(
    // in createSlice we guve three values name, initialState and reducers
    // reducers are like functions 
    {
        // The name of the slice, used as a prefix for generated action types
        name: "counter",
        //The initial state for the slice
        initialState,

        // The reducers field lets us define reducers and generate associated actions
        reducers: {
            // Define an increment reducer function to increase the counter value by 1
            increment : (state) =>{
                state.value += 1;
            },
            // Define a decrement reducer function to decrease the counter value by 1
            decrement: (state) =>{
                state.value -= 1;
            }
        }
    }
)

export const {increment, decrement } = CounterSlice.actions;

// This exports the action creators (increment and decrement) generated by createSlice. These can be dispatched to trigger the corresponding state updates.
export default CounterSlice.reducer;

// This exports the reducer function generated by createSlice, which will be used to configure the Redux store. The reducer function will handle actions related to the counter slice and update the state accordingly.



// https://chatgpt.com/share/97f2e62c-5178-4bbc-9f04-ed5e9efd7143 read this if cant understand